image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install_dependencies
  - test
  - build
  - deploy


dependencies:
  stage: install_dependencies
  script:
    - npm install

tsc:
  stage: test
  script:
    - npm install
    - npx tsc --noEmit

eslint:
  stage: test
  script:
    - npm install
    - npx eslint src/

npm_audit:
  stage: test
  script:
    - npm install
    - npm audit --json | npx @codejedi365/gitlab-npm-audit-parser -o
      gl-dependency-scanning.json
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning.json


docker_build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  when: manual



