image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install_dependencies
  - test
  - build
  - deploy


dependencies:
  stage: install_dependencies
  script:
    - npm install

tsc:
  stage: test
  script:
    - npm install
    - npx tsc --noEmit

eslint:
  stage: test
  script:
    - npm install
    - npx eslint src/

npm_audit:
  stage: test
  script:
    - npm install
    - npm audit --json | npx @codejedi365/gitlab-npm-audit-parser -o
      gl-dependency-scanning.json
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning.json




